### ISSUE TITLE
question: How keydb_affinity works?

### ISSUE THREAD

**Issue by qdrddr** [krestomatio/keydb-operator#159]
When in the CR I specify keydb_affinity, how does it work?
Can I set `requiredDuringSchedulingIgnoredDuringExecution`?

```yaml
---
apiVersion: keydb.krestomat.io/v1alpha1
kind: Keydb
metadata:
  name: iamdb-mm
spec:
  keydb_affinity: false
```

Is there documentation with a manifest with all available configuration options available with all possible values? Would be great to have examples with all possible options and allowed values.
This documentation is high-level and does not provide possible values https://krestomatio.com/docs/ansible-collection-k8s/roles/v1alpha1.database.keydb/defaults/main/keydb/#keydb_password

Thanks

**Comment by jobcespedes** [comment]
Hi, 

Yes, using `keydb_affinity` as a block string. Ex:
```
keydb_affinity: |-
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
```

For reference, [this](https://github.com/krestomatio/ansible-collection-k8s/blob/4110572329453541d7ab845b027894f795b33bc8/roles/v1alpha1/database/keydb/templates/sts/keydb-spec.yaml.j2#L160) is where is is defined in the respective template

**Comment by qdrddr** [comment]
this worked, thank you @jobcespedes!

```yaml
spe:
  keydb_affinity: |-
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:

            matchExpressions:
              - key: app.kubernetes.io/created_by
                operator: In
                values:
                  - keydb-operator
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - iamdb-mm
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - iamdb-mm-keydb
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - keydb
              - key: app.kubernetes.io/part-of
                operator: In
                values:
                  - iamdb-mm
```
